spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.112.142:3306/shiro-web?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: fanghuiping
    password: KKry100@qq.com

mybatis:
  type-aliases-package: com.example.cuava_cache.sys.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

swagger:
  title: 本地缓存
  description: 本地缓存
  version: 1.0.0
  name: 方慧平
  url: localhost:8080
  email: kkry100@qq.com
